jobs:
  build:
    permissions:
      contents: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: ncipollo/release-action@v1
      with:
        draft: true
        generateReleaseNotes: true
name: Github Release
on:
  repository_dispatch:
    types: trigger-ga___github-release.yml
