jobs:
  release:
    name: Site
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up Maven Central
      uses: actions/setup-java@v2
      with:
        cache: maven
        distribution: zulu
        java-version: 17
    - continue-on-error: true
      name: Generate website
      run: 'git config --global user.name ''${{ github.actor }}''

        git config --global user.email ''${{ github.actor }}@users.noreply.github.com''

        mvn install

        mvn site:site site:stage scm-publish:publish-scm -Dgithub.actor=${{ github.actor
        }} -Dgithub.token=${{ secrets.GITHUB_TOKEN }}

        '
name: mvn site
on:
  repository_dispatch:
    types: trigger-ga___mvn-site.yml
