jobs:
  release:
    name: Release to Maven Central
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up Maven Central
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        java-version: 11
        server-id: ossrh
        server-password: OSSRH_TOKEN
        server-username: OSSRH_USERNAME
    - continue-on-error: true
      env:
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      name: Publish to Maven Central
      run: 'git config user.name ''${{ github.actor }}''

        git config user.email ''${{ github.actor }}@users.noreply.github.com''

        mvn -B release:prepare release:perform -Dpassword=${{ secrets.GITHUB_TOKEN
        }}

        '
name: Release
on:
  repository_dispatch:
    types: trigger-ga___release.yml
